
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_1_DEVICE_ID,
		XPAR_AXI_GPIO_1_BASEADDR,
		XPAR_AXI_GPIO_1_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_1_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_A_DEVICE_ID,
		XPAR_AXI_GPIO_A_BASEADDR,
		XPAR_AXI_GPIO_A_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_A_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_B_DEVICE_ID,
		XPAR_AXI_GPIO_B_BASEADDR,
		XPAR_AXI_GPIO_B_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_B_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_OUT_0_DEVICE_ID,
		XPAR_AXI_GPIO_OUT_0_BASEADDR,
		XPAR_AXI_GPIO_OUT_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OUT_0_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_OUT_1_DEVICE_ID,
		XPAR_AXI_GPIO_OUT_1_BASEADDR,
		XPAR_AXI_GPIO_OUT_1_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OUT_1_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_RDY_DEVICE_ID,
		XPAR_AXI_GPIO_RDY_BASEADDR,
		XPAR_AXI_GPIO_RDY_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_RDY_IS_DUAL
	}
};


